/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import javax.swing.*;
import java.sql.*;

/**
 *
 * @author Huawei
 */
public class malzeme_ekle extends javax.swing.JFrame {

    /**
     * Creates new form frem
     */
    public malzeme_ekle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jTextField1 = new javax.swing.JTextField();
        toplam_miktar = new javax.swing.JTextField();
        malzeme_birimi = new javax.swing.JTextField();
        birim_fiyat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        toplam_miktar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toplam_miktarActionPerformed(evt);
            }
        });

        jLabel1.setText("Malzeme Adı");

        jLabel2.setText("Toplam Miktar");

        jLabel3.setText("Malzeme Birimi");

        jLabel4.setText("Birim Fiyatı");

        jButton3.setText("Ekle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(malzeme_birimi, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(birim_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(toplam_miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(toplam_miktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(malzeme_birimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(birim_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {
        // TODO add your handling code here:
    }

    private void toplam_miktarActionPerformed(java.awt.event.ActionEvent evt) {

    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Çalıştı");

        java.sql.Connection connection = null;
        DbHelper db = new DbHelper();
        PreparedStatement statement = null;
        ResultSet resultSet = null;

        try {
            // Veritabanı bağlantısı
            String url = "jdbc:mysql://localhost:3306/yemek";
            String user = "root";
            String password = "1234";

            connection = DriverManager.getConnection(url, user, password);

            // Malzeme adı duplicate kontrolü için sorgu
            String checkSql = "SELECT * FROM malzeme WHERE malzeme_adi = ?";
            statement = connection.prepareStatement(checkSql);
            statement.setString(1, jTextField1.getText());

            resultSet = statement.executeQuery();

            if (resultSet.next()) {
                // Aynı malzeme adı zaten mevcut
                JOptionPane.showMessageDialog(null, "Bu malzeme zaten mevcut: " + jTextField1.getText(),
                        "Duplicate Hatası", JOptionPane.WARNING_MESSAGE);
            } else {
                // Eğer malzeme mevcut değilse, ekleme işlemi yapılır
                String insertSql = "INSERT INTO malzeme (malzeme_adi, toplam_miktar, malzeme_birimi, birim_fiyat) VALUES (?, ?, ?, ?)";
                statement = connection.prepareStatement(insertSql, Statement.RETURN_GENERATED_KEYS);

                // Parametrelerin ayarlanması
                statement.setString(1, jTextField1.getText());
                statement.setString(2, toplam_miktar.getText());
                statement.setString(3, malzeme_birimi.getText());
                statement.setString(4, birim_fiyat.getText());

                // Sorguyu çalıştır
                int affectedRows = statement.executeUpdate();

                if (affectedRows > 0) {
                    JOptionPane.showMessageDialog(null, "Malzeme başarıyla eklendi:\n" +
                            "Malzeme Adı: " + jTextField1.getText() + "\n" +
                            "Toplam Miktar: " + toplam_miktar.getText() + "\n" +
                            "Malzeme Birimi: " + malzeme_birimi.getText() + "\n" +
                            "Birim Fiyatı: " + birim_fiyat.getText());
                } else {
                    JOptionPane.showMessageDialog(null, "Malzeme eklenemedi. Lütfen tekrar deneyin.");
                }
            }
        } catch (SQLException exception) {
            JOptionPane.showMessageDialog(null, "Hata oluştu: " + exception.getMessage());
        } finally {
            try {
                if (resultSet != null) resultSet.close();
                if (statement != null) statement.close();
                if (connection != null) connection.close();
            } catch (SQLException exception) {
                JOptionPane.showMessageDialog(null, "Bağlantı kapatma hatası: " + exception.getMessage());
            }
        }

        new ekleme_ekrani_2().setVisible(true);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(malzeme_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(malzeme_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(malzeme_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(malzeme_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new malzeme_ekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField birim_fiyat;
    private javax.swing.JButton jButton3;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField malzeme_birimi;
    private javax.swing.JTextField toplam_miktar;
    // End of variables declaration
}
